apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: db-helper
  name: db-helper
spec:
  replicas: 1
  selector:
    app: db-helper
    deploymentconfig: db-helper
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        app: db-helper
        deploymentconfig: db-helper
    spec:
      containers:
      - image: busybox
        name: db-helper
        restart: Never
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: pg-data
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "while :; do sleep 1; done"
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data
  test: false
