apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-int
  name: postgres-int
spec:
  ports:
  - name: postgres-int
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-int
    deploymentconfig: postgres-int