apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-int
  name: pg-data-int
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi