apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: teamdojo
  name: teamdojo
spec:
  lookupPolicy:
    local: false
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: teamdojo
  name: teamdojo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: teamdojo:latest
  source:
    git:
      ref: develop
      uri: https://github.com/iteratec/slab-dojo
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: openshift/Dockerfile
    type: Docker

